lr_scheduler:
  class: utils.schedule.OneCyclePolicy
  params:
    cycle_steps: ~
    pct_warm: 0.1
    max_lr: 0.003
    base_mom: 0.85
    max_mom: 0.95
    start_div_factor: 25.0
    end_div_factor: 1000.0