hydra:
  run:
    dir: /media/dmitry/data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

gpu: 1
seed: ~

out:
  num_images: 10266 # 3 times the original train length
  dir: /media/dmitry/data/global-wheat-detection/synthetic/0_25/${now:%Y-%m-%d}/${now:%H-%M-%S}
  ext: jpg

data:
  # params is passed to the dataset class __init__
  params:
    image_dir: /media/dmitry/data/global-wheat-detection/train
    csv: /media/dmitry/data/global-wheat-detection/train.csv
    source: ~
  loader:
    # batch size per each device
    batch_size: 10
    workers: 2
  transforms:
    normalize:
      class: albumentations.Normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    to_torch:
      class: albumentations.pytorch.transforms.ToTensorV2

model:
  class: models.style_augment.StyleAugmentNet
  params:
    img_channels: 3
    style_dim: 100
  alpha: 0.25
  weights: /media/dmitry/data/weights/style_augment_PBN_100.pth
