hydra:
  run:
    dir: /media/dmitry/data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model/effdet/base
  - model: effdet/tf_d4

gpu: 0
seed: ~
min_score: 0.07

out:
  dir: /media/dmitry/data/global-wheat-detection/prediction/${now:%Y-%m-%d}/${now:%H-%M-%S}
  file: submission.csv
  num_images: 32
  image_dir: images

data:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  class: data.no_labels.ImagesWithFileNames
  params:
    image_dir: /media/dmitry/data/global-wheat-detection/test
    metadata: true
  loader:
    batch_size: 5
    workers: 2
  transforms:
    resize:
      class: albumentations.Resize
      params:
        height: 768
        width: 768
        interpolation: 2  # INTER_CUBIC

model:
  class: models.efficient_det.create_model_from_config
  params:
    config:
      image_size: 768
      num_classes: 1
      pretrained_backbone: false
    bench_name: predict
    pretrained: false
    pretrained_backbone: false
  weights: /media/dmitry/data/weights/wheat/igor_002/checkpoint_6000_base.pth
