hydra:
  run:
    dir: /media/dmitry/data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model/effdet/base
  - model: effdet/tf_d5_640

gpu: 0
seed: ~
min_score: 0.065

tta:
  enabled: false
  iou_threshold: 0.55
  skip_threshold: 0.0

out:
  dir: /media/dmitry/data/global-wheat-detection/prediction/${now:%Y-%m-%d}/${now:%H-%M-%S}
  file: submission.csv
  num_images: 32
  image_dir: images

data:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  class: data.no_labels.ImagesWithFileNames
  params:
    image_dir: /media/dmitry/data/global-wheat-detection/test
    metadata: true
  loader:
    batch_size: 5
    workers: 2
  transforms:
    resize:
      class: albumentations.Resize
      params:
        height: 640
        width: 640
        interpolation: 2  # INTER_CUBIC

model:
  class: models.efficient_det.create_model_from_config
  params:
    config:
      num_classes: 1
      pretrained_backbone: false
      custom_nms: true
      nms_max_iou: 0.3
      nms_min_score: 0.05
    bench_name: predict
    pretrained: false
    pretrained_backbone: false
  weights: /media/dmitry/data/weights/wheat/009/checkpoint_17703_ema.pth
