model:
  params:
    config:
      name: efficientdet_d1
      backbone_name: efficientnet_b1
      backbone_args:
        drop_path_rate: 0.2
      image_size: 640
      fpn_channels: 88
      fpn_cell_repeats: 4
      box_class_repeats: 3
      pad_type: ''
      redundant_bias: false
      url: https://github.com/rwightman/efficientdet-pytorch/releases/download/v0.1/efficientdet_d1-bb7e98fe.pth
